/* Copyright (c) 2018, NIF File Format Library and Tools
All rights reserved.  Please see niflib.h for license. */

//---THIS FILE WAS AUTOMATICALLY GENERATED.  DO NOT EDIT---//

//To change this file, alter the niftools/docsys/gen_niflib.py Python script.

#pragma once

#include <gen/ByteMatrix.h>
#include <gen/ByteColor3.h>
#include <gen/LODRange.h>
#include <gen/MatchGroup.h>
#include <gen/ByteVector3.h>
#include <gen/HalfVector3.h>
#include <gen/hkQuaternion.h>
#include <gen/MipMap.h>
#include <gen/NodeSet.h>
#include <gen/SkinInfo.h>
#include <gen/SkinInfoSet.h>
#include <gen/BoneVertData.h>
#include <gen/AVObject.h>
#include <gen/ControlledBlock.h>
#include <gen/ExportInfo.h>
#include <gen/StringPalette.h>
#include <gen/TBC.h>
#include <gen/KeyGroup.h>
#include <gen/HalfTexCoord.h>
#include <gen/TexDesc.h>
#include <gen/ShaderTexDesc.h>
#include <gen/SkinPartition.h>
#include <gen/NiPlane.h>
#include <gen/NiBound.h>
#include <gen/NiQuatTransform.h>
#include <gen/NiTransform.h>
#include <gen/FurniturePosition.h>
#include <gen/TriangleData.h>
#include <gen/Morph.h>
#include <gen/Particle.h>
#include <gen/BoneData.h>
#include <gen/HavokFilter.h>
#include <gen/HavokMaterial.h>
#include <gen/OblivionSubShape.h>
#include <gen/bhkPositionConstraintMotor.h>
#include <gen/bhkVelocityConstraintMotor.h>
#include <gen/bhkSpringDamperConstraintMotor.h>
#include <gen/MotorDescriptor.h>
#include <gen/ReferenceSystemDescriptor.h>
#include <gen/JointLinkPoint.h>
#include <gen/JointAxisPoint.h>
#include <gen/RagdollDescriptor.h>
#include <gen/LimitedHingeDescriptor.h>
#include <gen/HingeDescriptor.h>
#include <gen/BallAndSocketDescriptor.h>
#include <gen/PrismaticDescriptor.h>
#include <gen/StiffSpringDescriptor.h>
#include <gen/OldSkinData.h>
#include <gen/BoxBV.h>
#include <gen/CapsuleBV.h>
#include <gen/HalfSpaceBV.h>
#include <gen/BoundingVolume.h>
#include <gen/UnionBV.h>
#include <gen/MorphWeight.h>
#include <gen/BoneTransform.h>
#include <gen/BonePose.h>
#include <gen/DecalVectorArray.h>
#include <gen/BodyPartList.h>
#include <gen/BoneLOD.h>
#include <gen/bhkCMSDMaterial.h>
#include <gen/bhkCMSDBigTris.h>
#include <gen/bhkCMSDTransform.h>
#include <gen/bhkCMSDChunk.h>
#include <gen/MalleableDescriptor.h>
#include <gen/ConstraintData.h>
#include <gen/hkWorldObjCinfoProperty.h>
#include <gen/ConstraintInfo.h>
#include <gen/InterpBlendItem.h>
#include <gen/MaterialData.h>
#include <gen/ParticleDesc.h>
#include <gen/PixelFormatComponent.h>
#include <gen/FormatPrefs.h>
#include <gen/PhysXMaterialRef.h>
#include <gen/PhysXStateName.h>
#include <gen/PhysXBodyStoredVels.h>
#include <gen/NiPhysXJointActor.h>
#include <gen/NxJointLimitSoftDesc.h>
#include <gen/NxJointDriveDesc.h>
#include <gen/NiPhysXJointLimit.h>
#include <gen/NxPlane.h>
#include <gen/NxCapsule.h>
#include <gen/NxSpringDesc.h>
#include <gen/NxMaterialDesc.h>
#include <gen/Polygon.h>
#include <gen/BSTreadTransform.h>
#include <gen/BSGeometrySubSegment.h>
#include <gen/BSGeometrySegmentData.h>
#include <gen/AdditionalDataInfo.h>
#include <gen/AdditionalDataBlock.h>
#include <gen/BSPackedAdditionalDataBlock.h>
#include <gen/Region.h>
#include <gen/SemanticData.h>
#include <gen/DataStreamRef.h>
#include <gen/ExtraMeshDataEpicMickey.h>
#include <gen/ExtraMeshDataEpicMickey2.h>
#include <gen/ElementReference.h>
#include <gen/LODInfo.h>
#include <gen/PSSpawnRateKey.h>
#include <gen/BSGeometryPerSegmentSharedData.h>
#include <gen/BSGeometrySegmentSharedData.h>
#include <gen/BSSkinBoneTrans.h>
#include <gen/BSConnectPoint.h>
#include <gen/BSPackedGeomDataCombined.h>
#include <gen/BSPackedGeomData.h>
#include <gen/BSPackedSharedGeomData.h>
#include <gen/BSPackedGeomObject.h>
#include <obj/NiObject.h>
#include <obj/Ni3dsAlphaAnimator.h>
#include <obj/Ni3dsAnimationNode.h>
#include <obj/Ni3dsColorAnimator.h>
#include <obj/Ni3dsMorphShape.h>
#include <obj/Ni3dsParticleSystem.h>
#include <obj/Ni3dsPathController.h>
#include <obj/NiParticleModifier.h>
#include <obj/NiPSysCollider.h>
#include <obj/bhkRefObject.h>
#include <obj/bhkSerializable.h>
#include <obj/bhkWorldObject.h>
#include <obj/bhkPhantom.h>
#include <obj/bhkShapePhantom.h>
#include <obj/bhkSimpleShapePhantom.h>
#include <obj/bhkEntity.h>
#include <obj/bhkRigidBody.h>
#include <obj/bhkRigidBodyT.h>
#include <obj/bhkConstraint.h>
#include <obj/bhkLimitedHingeConstraint.h>
#include <obj/bhkMalleableConstraint.h>
#include <obj/bhkStiffSpringConstraint.h>
#include <obj/bhkRagdollConstraint.h>
#include <obj/bhkPrismaticConstraint.h>
#include <obj/bhkHingeConstraint.h>
#include <obj/bhkBallAndSocketConstraint.h>
#include <obj/bhkBallSocketConstraintChain.h>
#include <obj/bhkShape.h>
#include <obj/bhkTransformShape.h>
#include <obj/bhkSphereRepShape.h>
#include <obj/bhkConvexShape.h>
#include <obj/bhkSphereShape.h>
#include <obj/bhkCapsuleShape.h>
#include <obj/bhkBoxShape.h>
#include <obj/bhkConvexVerticesShape.h>
#include <obj/bhkConvexTransformShape.h>
#include <obj/bhkConvexSweepShape.h>
#include <obj/bhkMultiSphereShape.h>
#include <obj/bhkBvTreeShape.h>
#include <obj/bhkMoppBvTreeShape.h>
#include <obj/bhkShapeCollection.h>
#include <obj/bhkListShape.h>
#include <obj/bhkMeshShape.h>
#include <obj/bhkPackedNiTriStripsShape.h>
#include <obj/bhkNiTriStripsShape.h>
#include <obj/NiExtraData.h>
#include <obj/NiInterpolator.h>
#include <obj/NiKeyBasedInterpolator.h>
#include <obj/NiFloatInterpolator.h>
#include <obj/NiTransformInterpolator.h>
#include <obj/NiPoint3Interpolator.h>
#include <obj/NiPathInterpolator.h>
#include <obj/NiBoolInterpolator.h>
#include <obj/NiBoolTimelineInterpolator.h>
#include <obj/NiBlendInterpolator.h>
#include <obj/NiBSplineInterpolator.h>
#include <obj/NiObjectNET.h>
#include <obj/NiCollisionObject.h>
#include <obj/NiCollisionData.h>
#include <obj/bhkNiCollisionObject.h>
#include <obj/bhkCollisionObject.h>
#include <obj/bhkBlendCollisionObject.h>
#include <obj/bhkPCollisionObject.h>
#include <obj/bhkSPCollisionObject.h>
#include <obj/NiAVObject.h>
#include <obj/NiDynamicEffect.h>
#include <obj/NiLight.h>
#include <obj/NiProperty.h>
#include <obj/NiTransparentProperty.h>
#include <obj/NiPSysModifier.h>
#include <obj/NiPSysEmitter.h>
#include <obj/NiPSysVolumeEmitter.h>
#include <obj/NiTimeController.h>
#include <obj/NiInterpController.h>
#include <obj/NiMultiTargetTransformController.h>
#include <obj/NiGeomMorpherController.h>
#include <obj/NiMorphController.h>
#include <obj/NiMorpherController.h>
#include <obj/NiSingleInterpController.h>
#include <obj/NiKeyframeController.h>
#include <obj/NiTransformController.h>
#include <obj/NiPSysModifierCtlr.h>
#include <obj/NiPSysEmitterCtlr.h>
#include <obj/NiPSysModifierBoolCtlr.h>
#include <obj/NiPSysModifierActiveCtlr.h>
#include <obj/NiPSysModifierFloatCtlr.h>
#include <obj/NiPSysEmitterDeclinationCtlr.h>
#include <obj/NiPSysEmitterDeclinationVarCtlr.h>
#include <obj/NiPSysEmitterInitialRadiusCtlr.h>
#include <obj/NiPSysEmitterLifeSpanCtlr.h>
#include <obj/NiPSysEmitterSpeedCtlr.h>
#include <obj/NiPSysGravityStrengthCtlr.h>
#include <obj/NiFloatInterpController.h>
#include <obj/NiFlipController.h>
#include <obj/NiAlphaController.h>
#include <obj/NiTextureTransformController.h>
#include <obj/NiLightDimmerController.h>
#include <obj/NiBoolInterpController.h>
#include <obj/NiVisController.h>
#include <obj/NiPoint3InterpController.h>
#include <obj/NiMaterialColorController.h>
#include <obj/NiLightColorController.h>
#include <obj/NiExtraDataController.h>
#include <obj/NiFloatExtraDataController.h>
#include <obj/NiFloatsExtraDataController.h>
#include <obj/NiFloatsExtraDataPoint3Controller.h>
#include <obj/NiBoneLODController.h>
#include <obj/NiBSBoneLODController.h>
#include <obj/NiGeometry.h>
#include <obj/NiTriBasedGeom.h>
#include <obj/NiGeometryData.h>
#include <obj/AbstractAdditionalGeometryData.h>
#include <obj/NiTriBasedGeomData.h>
#include <obj/bhkBlendController.h>
#include <obj/BSBound.h>
#include <obj/BSFurnitureMarker.h>
#include <obj/BSParentVelocityModifier.h>
#include <obj/BSPSysArrayEmitter.h>
#include <obj/BSWindModifier.h>
#include <obj/hkPackedNiTriStripsData.h>
#include <obj/NiAlphaProperty.h>
#include <obj/NiAmbientLight.h>
#include <obj/NiParticlesData.h>
#include <obj/NiRotatingParticlesData.h>
#include <obj/NiAutoNormalParticlesData.h>
#include <obj/NiPSysData.h>
#include <obj/NiMeshPSysData.h>
#include <obj/NiBinaryExtraData.h>
#include <obj/NiBinaryVoxelExtraData.h>
#include <obj/NiBinaryVoxelData.h>
#include <obj/NiBlendBoolInterpolator.h>
#include <obj/NiBlendFloatInterpolator.h>
#include <obj/NiBlendPoint3Interpolator.h>
#include <obj/NiBlendTransformInterpolator.h>
#include <obj/NiBoolData.h>
#include <obj/NiBooleanExtraData.h>
#include <obj/NiBSplineBasisData.h>
#include <obj/NiBSplineFloatInterpolator.h>
#include <obj/NiBSplineCompFloatInterpolator.h>
#include <obj/NiBSplinePoint3Interpolator.h>
#include <obj/NiBSplineCompPoint3Interpolator.h>
#include <obj/NiBSplineTransformInterpolator.h>
#include <obj/NiBSplineCompTransformInterpolator.h>
#include <obj/BSRotAccumTransfInterpolator.h>
#include <obj/NiBSplineData.h>
#include <obj/NiCamera.h>
#include <obj/NiColorData.h>
#include <obj/NiColorExtraData.h>
#include <obj/NiControllerManager.h>
#include <obj/NiSequence.h>
#include <obj/NiControllerSequence.h>
#include <obj/NiAVObjectPalette.h>
#include <obj/NiDefaultAVObjectPalette.h>
#include <obj/NiDirectionalLight.h>
#include <obj/NiDitherProperty.h>
#include <obj/NiRollController.h>
#include <obj/NiFloatData.h>
#include <obj/NiFloatExtraData.h>
#include <obj/NiFloatsExtraData.h>
#include <obj/NiFogProperty.h>
#include <obj/NiGravity.h>
#include <obj/NiIntegerExtraData.h>
#include <obj/BSXFlags.h>
#include <obj/NiIntegersExtraData.h>
#include <obj/BSKeyframeController.h>
#include <obj/NiKeyframeData.h>
#include <obj/NiLookAtController.h>
#include <obj/NiLookAtInterpolator.h>
#include <obj/NiMaterialProperty.h>
#include <obj/NiMorphData.h>
#include <obj/NiNode.h>
#include <obj/NiBone.h>
#include <obj/AvoidNode.h>
#include <obj/FxWidget.h>
#include <obj/FxButton.h>
#include <obj/FxRadioButton.h>
#include <obj/NiBillboardNode.h>
#include <obj/NiBSAnimationNode.h>
#include <obj/NiBSParticleNode.h>
#include <obj/NiSwitchNode.h>
#include <obj/NiLODNode.h>
#include <obj/NiPalette.h>
#include <obj/NiParticleBomb.h>
#include <obj/NiParticleColorModifier.h>
#include <obj/NiParticleGrowFade.h>
#include <obj/NiParticleMeshModifier.h>
#include <obj/NiParticleRotation.h>
#include <obj/NiParticles.h>
#include <obj/NiAutoNormalParticles.h>
#include <obj/NiParticleMeshes.h>
#include <obj/NiParticleMeshesData.h>
#include <obj/NiParticleSystem.h>
#include <obj/NiMeshParticleSystem.h>
#include <obj/NiParticleSystemController.h>
#include <obj/NiBSPArrayController.h>
#include <obj/NiPathController.h>
#include <obj/NiPixelFormat.h>
#include <obj/NiPersistentSrcTextureRendererData.h>
#include <obj/NiPixelData.h>
#include <obj/NiPlanarCollider.h>
#include <obj/NiPointLight.h>
#include <obj/NiPosData.h>
#include <obj/NiRotData.h>
#include <obj/NiPSysAgeDeathModifier.h>
#include <obj/NiPSysBombModifier.h>
#include <obj/NiPSysBoundUpdateModifier.h>
#include <obj/NiPSysBoxEmitter.h>
#include <obj/NiPSysColliderManager.h>
#include <obj/NiPSysColorModifier.h>
#include <obj/NiPSysCylinderEmitter.h>
#include <obj/NiPSysDragModifier.h>
#include <obj/NiPSysEmitterCtlrData.h>
#include <obj/NiPSysGravityModifier.h>
#include <obj/NiPSysGrowFadeModifier.h>
#include <obj/NiPSysMeshEmitter.h>
#include <obj/NiPSysMeshUpdateModifier.h>
#include <obj/BSPSysInheritVelocityModifier.h>
#include <obj/BSPSysHavokUpdateModifier.h>
#include <obj/BSPSysRecycleBoundModifier.h>
#include <obj/BSPSysSubTexModifier.h>
#include <obj/NiPSysPlanarCollider.h>
#include <obj/NiPSysSphericalCollider.h>
#include <obj/NiPSysPositionModifier.h>
#include <obj/NiPSysResetOnLoopCtlr.h>
#include <obj/NiPSysRotationModifier.h>
#include <obj/NiPSysSpawnModifier.h>
#include <obj/NiPSysSphereEmitter.h>
#include <obj/NiPSysUpdateCtlr.h>
#include <obj/NiPSysFieldModifier.h>
#include <obj/NiPSysVortexFieldModifier.h>
#include <obj/NiPSysGravityFieldModifier.h>
#include <obj/NiPSysDragFieldModifier.h>
#include <obj/NiPSysTurbulenceFieldModifier.h>
#include <obj/BSPSysLODModifier.h>
#include <obj/BSPSysScaleModifier.h>
#include <obj/NiPSysFieldMagnitudeCtlr.h>
#include <obj/NiPSysFieldAttenuationCtlr.h>
#include <obj/NiPSysFieldMaxDistanceCtlr.h>
#include <obj/NiPSysAirFieldAirFrictionCtlr.h>
#include <obj/NiPSysAirFieldInheritVelocityCtlr.h>
#include <obj/NiPSysAirFieldSpreadCtlr.h>
#include <obj/NiPSysInitialRotSpeedCtlr.h>
#include <obj/NiPSysInitialRotSpeedVarCtlr.h>
#include <obj/NiPSysInitialRotAngleCtlr.h>
#include <obj/NiPSysInitialRotAngleVarCtlr.h>
#include <obj/NiPSysEmitterPlanarAngleCtlr.h>
#include <obj/NiPSysEmitterPlanarAngleVarCtlr.h>
#include <obj/NiPSysAirFieldModifier.h>
#include <obj/NiPSysTrailEmitter.h>
#include <obj/NiLightIntensityController.h>
#include <obj/NiPSysRadialFieldModifier.h>
#include <obj/NiLODData.h>
#include <obj/NiRangeLODData.h>
#include <obj/NiScreenLODData.h>
#include <obj/NiRotatingParticles.h>
#include <obj/NiSequenceStreamHelper.h>
#include <obj/NiShadeProperty.h>
#include <obj/NiSkinData.h>
#include <obj/NiSkinInstance.h>
#include <obj/NiTriShapeSkinController.h>
#include <obj/NiClodSkinInstance.h>
#include <obj/NiSkinPartition.h>
#include <obj/NiTexture.h>
#include <obj/NiSourceTexture.h>
#include <obj/NiSpecularProperty.h>
#include <obj/NiSphericalCollider.h>
#include <obj/NiSpotLight.h>
#include <obj/NiStencilProperty.h>
#include <obj/NiStringExtraData.h>
#include <obj/NiStringPalette.h>
#include <obj/NiStringsExtraData.h>
#include <obj/NiTextKeyExtraData.h>
#include <obj/NiTextureEffect.h>
#include <obj/NiTextureModeProperty.h>
#include <obj/NiImage.h>
#include <obj/NiTextureProperty.h>
#include <obj/NiTexturingProperty.h>
#include <obj/NiMultiTextureProperty.h>
#include <obj/NiTransformData.h>
#include <obj/NiTriShape.h>
#include <obj/NiTriShapeData.h>
#include <obj/NiTriStrips.h>
#include <obj/NiTriStripsData.h>
#include <obj/NiEnvMappedTriShape.h>
#include <obj/NiEnvMappedTriShapeData.h>
#include <obj/NiBezierTriangle4.h>
#include <obj/NiBezierMesh.h>
#include <obj/NiClod.h>
#include <obj/NiClodData.h>
#include <obj/NiUVController.h>
#include <obj/NiUVData.h>
#include <obj/NiVectorExtraData.h>
#include <obj/NiVertexColorProperty.h>
#include <obj/NiVertWeightsExtraData.h>
#include <obj/NiVisData.h>
#include <obj/NiWireframeProperty.h>
#include <obj/NiZBufferProperty.h>
#include <obj/RootCollisionNode.h>
#include <obj/NiRawImageData.h>
#include <obj/NiAccumulator.h>
#include <obj/NiSortAdjustNode.h>
#include <obj/NiSourceCubeMap.h>
#include <obj/NiPhysXProp.h>
#include <obj/NiPhysXPropDesc.h>
#include <obj/NiPhysXActorDesc.h>
#include <obj/NiPhysXBodyDesc.h>
#include <obj/NiPhysXJointDesc.h>
#include <obj/NiPhysXD6JointDesc.h>
#include <obj/NiPhysXShapeDesc.h>
#include <obj/NiPhysXMeshDesc.h>
#include <obj/NiPhysXMaterialDesc.h>
#include <obj/NiPhysXDest.h>
#include <obj/NiPhysXRigidBodyDest.h>
#include <obj/NiPhysXTransformDest.h>
#include <obj/NiPhysXSrc.h>
#include <obj/NiPhysXRigidBodySrc.h>
#include <obj/NiPhysXKinematicSrc.h>
#include <obj/NiPhysXDynamicSrc.h>
#include <obj/NiLines.h>
#include <obj/NiLinesData.h>
#include <obj/NiScreenElementsData.h>
#include <obj/NiScreenElements.h>
#include <obj/NiRoomGroup.h>
#include <obj/NiRoom.h>
#include <obj/NiPortal.h>
#include <obj/BSFadeNode.h>
#include <obj/BSShaderProperty.h>
#include <obj/BSShaderLightingProperty.h>
#include <obj/BSShaderNoLightingProperty.h>
#include <obj/BSShaderPPLightingProperty.h>
#include <obj/BSEffectShaderPropertyFloatController.h>
#include <obj/BSEffectShaderPropertyColorController.h>
#include <obj/BSLightingShaderPropertyFloatController.h>
#include <obj/BSLightingShaderPropertyColorController.h>
#include <obj/BSNiAlphaPropertyTestRefController.h>
#include <obj/BSProceduralLightningController.h>
#include <obj/BSShaderTextureSet.h>
#include <obj/WaterShaderProperty.h>
#include <obj/SkyShaderProperty.h>
#include <obj/TileShaderProperty.h>
#include <obj/DistantLODShaderProperty.h>
#include <obj/BSDistantTreeShaderProperty.h>
#include <obj/TallGrassShaderProperty.h>
#include <obj/VolumetricFogShaderProperty.h>
#include <obj/HairShaderProperty.h>
#include <obj/Lighting30ShaderProperty.h>
#include <obj/BSLightingShaderProperty.h>
#include <obj/BSEffectShaderProperty.h>
#include <obj/BSWaterShaderProperty.h>
#include <obj/BSSkyShaderProperty.h>
#include <obj/BSDismemberSkinInstance.h>
#include <obj/BSDecalPlacementVectorExtraData.h>
#include <obj/BSPSysSimpleColorModifier.h>
#include <obj/BSValueNode.h>
#include <obj/BSStripParticleSystem.h>
#include <obj/BSStripPSysData.h>
#include <obj/BSPSysStripUpdateModifier.h>
#include <obj/BSMaterialEmittanceMultController.h>
#include <obj/BSMasterParticleSystem.h>
#include <obj/BSPSysMultiTargetEmitterCtlr.h>
#include <obj/BSRefractionStrengthController.h>
#include <obj/BSOrderedNode.h>
#include <obj/BSRangeNode.h>
#include <obj/BSBlastNode.h>
#include <obj/BSDamageStage.h>
#include <obj/BSRefractionFirePeriodController.h>
#include <obj/bhkConvexListShape.h>
#include <obj/BSTreadTransfInterpolator.h>
#include <obj/BSAnimNote.h>
#include <obj/BSAnimNotes.h>
#include <obj/bhkLiquidAction.h>
#include <obj/BSMultiBoundNode.h>
#include <obj/BSMultiBound.h>
#include <obj/BSMultiBoundData.h>
#include <obj/BSMultiBoundOBB.h>
#include <obj/BSMultiBoundSphere.h>
#include <obj/BSSegmentedTriShape.h>
#include <obj/BSMultiBoundAABB.h>
#include <obj/NiAdditionalGeometryData.h>
#include <obj/BSPackedAdditionalGeometryData.h>
#include <obj/BSWArray.h>
#include <obj/bhkAabbPhantom.h>
#include <obj/BSFrustumFOVController.h>
#include <obj/BSDebrisNode.h>
#include <obj/bhkBreakableConstraint.h>
#include <obj/bhkOrientHingedBodyAction.h>
#include <obj/bhkPoseArray.h>
#include <obj/bhkRagdollTemplate.h>
#include <obj/bhkRagdollTemplateData.h>
#include <obj/NiDataStream.h>
#include <obj/NiRenderObject.h>
#include <obj/NiMeshModifier.h>
#include <obj/NiMesh.h>
#include <obj/NiMorphWeightsController.h>
#include <obj/NiMorphMeshModifier.h>
#include <obj/NiSkinningMeshModifier.h>
#include <obj/NiMeshHWInstance.h>
#include <obj/NiInstancingMeshModifier.h>
#include <obj/NiSkinningLODController.h>
#include <obj/NiPSParticleSystem.h>
#include <obj/NiPSMeshParticleSystem.h>
#include <obj/NiPSFacingQuadGenerator.h>
#include <obj/NiPSAlignedQuadGenerator.h>
#include <obj/NiPSSimulator.h>
#include <obj/NiPSSimulatorStep.h>
#include <obj/NiPSSimulatorGeneralStep.h>
#include <obj/NiPSSimulatorForcesStep.h>
#include <obj/NiPSSimulatorCollidersStep.h>
#include <obj/NiPSSimulatorMeshAlignStep.h>
#include <obj/NiPSSimulatorFinalStep.h>
#include <obj/NiPSBoundUpdater.h>
#include <obj/NiPSForce.h>
#include <obj/NiPSDragForce.h>
#include <obj/NiPSGravityForce.h>
#include <obj/NiPSBombForce.h>
#include <obj/NiPSEmitter.h>
#include <obj/NiPSVolumeEmitter.h>
#include <obj/NiPSBoxEmitter.h>
#include <obj/NiPSSphereEmitter.h>
#include <obj/NiPSCylinderEmitter.h>
#include <obj/NiPSMeshEmitter.h>
#include <obj/NiPSEmitterCtlr.h>
#include <obj/NiPSEmitterFloatCtlr.h>
#include <obj/NiPSEmitParticlesCtlr.h>
#include <obj/NiPSForceCtlr.h>
#include <obj/NiPSForceBoolCtlr.h>
#include <obj/NiPSForceFloatCtlr.h>
#include <obj/NiPSForceActiveCtlr.h>
#include <obj/NiPSGravityStrengthCtlr.h>
#include <obj/NiPSEmitterSpeedCtlr.h>
#include <obj/NiPSEmitterRadiusCtlr.h>
#include <obj/NiPSEmitterDeclinationCtlr.h>
#include <obj/NiPSEmitterDeclinationVarCtlr.h>
#include <obj/NiPSEmitterPlanarAngleCtlr.h>
#include <obj/NiPSEmitterPlanarAngleVarCtlr.h>
#include <obj/NiPSEmitterRotAngleCtlr.h>
#include <obj/NiPSEmitterRotAngleVarCtlr.h>
#include <obj/NiPSEmitterRotSpeedCtlr.h>
#include <obj/NiPSEmitterRotSpeedVarCtlr.h>
#include <obj/NiPSEmitterLifeSpanCtlr.h>
#include <obj/NiPSResetOnLoopCtlr.h>
#include <obj/NiPSCollider.h>
#include <obj/NiPSPlanarCollider.h>
#include <obj/NiPSSphericalCollider.h>
#include <obj/NiPSSpawner.h>
#include <obj/NiEvaluator.h>
#include <obj/NiKeyBasedEvaluator.h>
#include <obj/NiBoolEvaluator.h>
#include <obj/NiBoolTimelineEvaluator.h>
#include <obj/NiColorEvaluator.h>
#include <obj/NiFloatEvaluator.h>
#include <obj/NiPoint3Evaluator.h>
#include <obj/NiQuaternionEvaluator.h>
#include <obj/NiTransformEvaluator.h>
#include <obj/NiConstBoolEvaluator.h>
#include <obj/NiConstColorEvaluator.h>
#include <obj/NiConstFloatEvaluator.h>
#include <obj/NiConstPoint3Evaluator.h>
#include <obj/NiConstQuaternionEvaluator.h>
#include <obj/NiConstTransformEvaluator.h>
#include <obj/NiBSplineEvaluator.h>
#include <obj/NiBSplineColorEvaluator.h>
#include <obj/NiBSplineCompColorEvaluator.h>
#include <obj/NiBSplineFloatEvaluator.h>
#include <obj/NiBSplineCompFloatEvaluator.h>
#include <obj/NiBSplinePoint3Evaluator.h>
#include <obj/NiBSplineCompPoint3Evaluator.h>
#include <obj/NiBSplineTransformEvaluator.h>
#include <obj/NiBSplineCompTransformEvaluator.h>
#include <obj/NiLookAtEvaluator.h>
#include <obj/NiPathEvaluator.h>
#include <obj/NiSequenceData.h>
#include <obj/NiShadowGenerator.h>
#include <obj/NiFurSpringController.h>
#include <obj/CStreamableAssetData.h>
#include <obj/bhkCompressedMeshShape.h>
#include <obj/bhkCompressedMeshShapeData.h>
#include <obj/BSInvMarker.h>
#include <obj/BSBoneLODExtraData.h>
#include <obj/BSBehaviorGraphExtraData.h>
#include <obj/BSLagBoneController.h>
#include <obj/BSLODTriShape.h>
#include <obj/BSFurnitureMarkerNode.h>
#include <obj/BSLeafAnimNode.h>
#include <obj/BSTreeNode.h>
#include <obj/BSTriShape.h>
#include <obj/BSMeshLODTriShape.h>
#include <obj/BSSubIndexTriShape.h>
#include <obj/bhkSystem.h>
#include <obj/bhkNPCollisionObject.h>
#include <obj/bhkPhysicsSystem.h>
#include <obj/bhkRagdollSystem.h>
#include <obj/BSExtraData.h>
#include <obj/BSClothExtraData.h>
#include <obj/BSSkin__Instance.h>
#include <obj/BSSkin__BoneData.h>
#include <obj/BSPositionData.h>
#include <obj/BSConnectPoint__Parents.h>
#include <obj/BSConnectPoint__Children.h>
#include <obj/BSEyeCenterExtraData.h>
#include <obj/BSPackedCombinedGeomDataExtra.h>
#include <obj/BSPackedCombinedSharedGeomDataExtra.h>
#include <obj/NiLightRadiusController.h>
#include <obj/BSDynamicTriShape.h>
#include <obj/BSDistantObjectLargeRefExtraData.h>
